# Generated by Django 4.2.6 on 2023-10-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DistanceBaseTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_base_tier_distance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('dbp', models.IntegerField()),
                ('config_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.config')),
            ],
            options={
                'db_table': 'distance-base-tier-pricing',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'days_of_week',
            },
        ),
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_mins', models.IntegerField()),
                ('per_min_charge', models.DecimalField(decimal_places=2, max_digits=4)),
                ('config_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.config', unique=True)),
            ],
            options={
                'db_table': 'waiting-charges',
            },
        ),
        migrations.CreateModel(
            name='DistanceBaseTierWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_base_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.distancebasetier')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.week')),
            ],
        ),
        migrations.AddField(
            model_name='distancebasetier',
            name='selected_days',
            field=models.ManyToManyField(through='pricing.DistanceBaseTierWeek', to='pricing.week'),
        ),
        migrations.CreateModel(
            name='DistanceAdditionalTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_km_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('config_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.config', unique=True)),
            ],
            options={
                'db_table': 'additional-distance-tier-pricing',
            },
        ),
    ]
