# Generated by Django 4.2.6 on 2023-10-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='distancebasetierweek',
            table='distance-base-tier-week',
        ),
    ]
