# Generated by Django 4.2.6 on 2023-10-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_distancebasetierweek_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_tier_time', models.CharField()),
                ('end_tier_time', models.CharField()),
                ('time_multiplier_factor', models.DecimalField(decimal_places=3, max_digits=5)),
                ('config_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.config')),
            ],
            options={
                'db_table': 'time-tier-pricing',
            },
        ),
    ]
