# Generated by Django 4.2.6 on 2023-10-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_distancebasetierweek_config_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancebasetierweek',
            name='config_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pricing.config'),
        ),
    ]
